spring:
  application:
    name: suqiu-order
  datasource:
    url: jdbc:mysql://101.33.230.220:3306/suqiu_order
    username: root
    password: suqiu
  cloud:
    nacos:
      discovery:
        server-addr: 106.52.18.157:8848
server:
  port: 8081

ribbon:
  # 值的是建立连接所用的时间，使用与网络状态正常的情况，两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectionTimeout: 5000